bounding_box_chessboard:
  top: 60
  left: 485
  width: 888
  height: 888
  color: [205, 171]  # colors of a cell after move that relates to it  # 170 moved to 171

bounding_box_timer:
  top: 713
  left: 1396
  width: 197
  height: 57
  color: [56, 121]  # colors of a timer when my turn when player has time and when time is low

my_green_circle:
  top: 689
  left: 1411
  width: 4
  height: 4
  color: 92

opponent_green_circle:
  top: 460
  left: 1411
  width: 4
  height: 4
  color: 92

takeback_red_cross:
  top: 640
  left: 1416
  width: 18
  height: 18
  color: 187  # color of a red cross to decline takeback

draw_offer_red_cross:
  top: 640
  left: 1421
  width: 18
  height: 18
  color: 187  # color of a red cross to decline draw offer

afk_gray_green_circle:
  top: 437
  left: 1421
  width: 4
  height: 4
  color: 38  # color inside afk player's circle

defeat_afk_opponent_blue_box:
  top: 660
  left: 1450
  width: 9
  height: 9
  color: 54

hard_restart_acceptance_box:  # Leave page blue box
  top: 570
  left: 962
  width: 4
  height: 4
  color: 0
